services:
  app:
    image: dalloglio/rust-with-stellar-cli:local
    container_name: app
    working_dir: /home/bob/app/soroban
    volumes:
      - .:/home/bob/app
  
  stellar:
    image: stellar/quickstart:testing
    container_name: stellar
    ports:
      - "8000:8000"
    command: ["--local"]
